
package epa;
import javax.swing.*;
import java.awt.*;

public class EPAmain extends JFrame {
    
    Toolkit tk = Toolkit.getDefaultToolkit();
    Dimension d = tk.getScreenSize();
    
    public EPAmain() {
        initComponents();
        this.setTitle("Sample Menu Driven App");
        int x = (d.width-this.getWidth())/2;
        int y = (d.height-this.getHeight())/2;
        this.setLocation(x,y);
        
       utility.DBConnection.connection();
        displayForm(new Login(jplMain,mnuBar,mnuRegistration,mnuPrint));      
    }

    public void displayForm(JPanel jp){
        jplMain.removeAll();
        jplMain.add(jp);
        jplMain.validate();
        jplMain.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplMain = new javax.swing.JPanel();
        mnuBar = new javax.swing.JMenuBar();
        mnuRecords = new javax.swing.JMenu();
        mnuRegistration = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuInventory = new javax.swing.JMenuItem();
        mnuPrint = new javax.swing.JMenu();
        mnuSales = new javax.swing.JMenuItem();
        mnuUsers = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuSwitch = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jplMain.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jplMainLayout = new javax.swing.GroupLayout(jplMain);
        jplMain.setLayout(jplMainLayout);
        jplMainLayout.setHorizontalGroup(
            jplMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1064, Short.MAX_VALUE)
        );
        jplMainLayout.setVerticalGroup(
            jplMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        mnuRecords.setText("Records");

        mnuRegistration.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK));
        mnuRegistration.setText("Registration");
        mnuRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistrationActionPerformed(evt);
            }
        });
        mnuRecords.add(mnuRegistration);
        mnuRecords.add(jSeparator1);

        mnuInventory.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK));
        mnuInventory.setText("Inventory");
        mnuInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInventoryActionPerformed(evt);
            }
        });
        mnuRecords.add(mnuInventory);

        mnuBar.add(mnuRecords);

        mnuPrint.setText("Print");

        mnuSales.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuSales.setText("Sales");
        mnuSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalesActionPerformed(evt);
            }
        });
        mnuPrint.add(mnuSales);
        mnuPrint.add(mnuUsers);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Users");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuPrint.add(jMenuItem1);

        mnuBar.add(mnuPrint);

        jMenu1.setText("Users");

        jMenuItem2.setText("Change Password");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator2);

        mnuSwitch.setText("Switch User");
        mnuSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSwitchActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSwitch);

        mnuBar.add(jMenu1);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jplMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean closeOption(){
        if (utility.Utility.universalCode==1){
            int res=JOptionPane.showConfirmDialog(null, "Do you want to save your work?","Warning",JOptionPane.YES_NO_OPTION);
            if (res==JOptionPane.YES_OPTION){
                return false;
            }else{
                utility.Utility.universalCode=0;
                return true;
            }
        }else{
            return true;
        }
    }
    private void mnuSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalesActionPerformed
        if (closeOption()){
            displayForm(new jplSales(jplMain));
        }
    }//GEN-LAST:event_mnuSalesActionPerformed

    private void mnuRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistrationActionPerformed
        if (closeOption()){
            displayForm(new jplRegistration(jplMain));
        }
    }//GEN-LAST:event_mnuRegistrationActionPerformed

    private void mnuInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInventoryActionPerformed
        if (closeOption()){
            displayForm(new jplInventory(jplMain));
        }
    }//GEN-LAST:event_mnuInventoryActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (closeOption()){
            displayForm(new jplUsers(jplMain));
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnuSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSwitchActionPerformed
        if (closeOption()){
            displayForm(new Login(jplMain,mnuBar,mnuRegistration,mnuPrint));      
        }
    }//GEN-LAST:event_mnuSwitchActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         if (closeOption()){
            displayForm(new jplChangePassword(jplMain));
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param  the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EPAmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EPAmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EPAmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EPAmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EPAmain().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPanel jplMain;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenuItem mnuInventory;
    private javax.swing.JMenu mnuPrint;
    private javax.swing.JMenu mnuRecords;
    private javax.swing.JMenuItem mnuRegistration;
    private javax.swing.JMenuItem mnuSales;
    private javax.swing.JMenuItem mnuSwitch;
    private javax.swing.JPopupMenu.Separator mnuUsers;
    // End of variables declaration//GEN-END:variables
}
